import React from 'react';

const commonStyles = {
  h3: "text-xl font-bold text-brand-text-primary mt-6 mb-2",
  p: "text-brand-text-secondary mb-4",
  ul: "list-disc list-inside text-brand-text-secondary space-y-2 mb-4",
  li: "",
}

export const TermsAndConditions: React.FC = () => (
    <div className="prose prose-sm max-w-none text-brand-text-secondary">
        <p className={commonStyles.p}>Last updated: {new Date().toLocaleDateString()}</p>
        
        <h3 className={commonStyles.h3}>1. Acceptance of Terms</h3>
        <p className={commonStyles.p}>By accessing or using the WinkDrops application ("Service"), you agree to be bound by these Terms and Conditions ("Terms"). If you disagree with any part of the terms, then you may not access the Service.</p>
        
        <h3 className={commonStyles.h3}>2. Service Description</h3>
        <p className={commonStyles.p}>WinkDrops allows users to send anonymous messages of concern ("Winks") containing AI-generated content. The service is intended as a tool to encourage supportive communication and is explicitly not for medical or emergency use.</p>
        
        <h3 className={commonStyles.h3}>3. No Medical Advice Disclaimer</h3>
        <p className={commonStyles.p}>The content provided by WinkDrops, whether generated by AI or otherwise, does not constitute medical advice, diagnosis, or treatment. It is for informational purposes only. You must always seek the advice of a qualified health professional for any medical concerns. Never disregard professional medical advice or delay in seeking it because of something you have read on WinkDrops. For any mental health emergency, please contact a crisis hotline or emergency services immediately.</p>
        
        <h3 className={commonStyles.h3}>4. Limitation of Liability</h3>
        <p className={commonStyles.p}>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. To the maximum extent permitted by applicable law, in no event shall WinkDrops, its creators, or affiliates be liable for any direct, indirect, incidental, special, consequential, or punitive damages—including but not to, damages for loss of profits, goodwill, use, data, or other intangible losses—resulting from your use of, or inability to use, the Service. You assume full and total responsibility for your use of the platform and any consequences arising from it.</p>
        
        <h3 className={commonStyles.h3}>5. User Conduct</h3>
        <p className={commonStyles.p}>You agree not to use WinkDrops for any unlawful purpose or to engage in any activity that is harmful, threatening, abusive, harassing, defamatory, or invasive of another's privacy. We reserve the right to terminate access for any user who violates these terms.</p>
    </div>
);

export const PrivacyPolicy: React.FC = () => (
    <div className="prose prose-sm max-w-none text-brand-text-secondary">
        <p className={commonStyles.p}>Last updated: {new Date().toLocaleDateString()}</p>
        
        <h3 className={commonStyles.h3}>1. Information Collection and Use</h3>
        <p className={commonStyles.p}>WinkDrops is designed to prioritize your privacy. We do not require account creation, and we do not collect or store any personally identifiable information (PII) on our servers. All data you generate, including inbox and outbox messages, is stored locally in your browser's storage and is under your control.</p>
        
        <h3 className={commonStyles.h3}>2. Anonymity</h3>
        <p className={commonStyles.p}>The core feature of WinkDrops is anonymity. We have no technical means to track who sends a Wink. We encourage users to be mindful not to include any self-identifying details in the content they create to maintain their own privacy.</p>
        
        <h3 className={commonStyles.h3}>3. Third-Party AI Services</h3>
        <p className={commonStyles.p}>To generate content, we send the non-personal, observational data you select to third-party AI models (such as Google's Gemini API). This data is not linked to you or the recipient in any identifiable way. We recommend reviewing the privacy policies of these third-party services for information on how they handle data.</p>

        <h3 className={commonStyles.h3}>4. Geolocation Data</h3>
        <p className={commonStyles.p}>If you choose to use features that find local resources, we will request one-time access to your browser's geolocation data. This information is sent to the AI service to perform the search and is not stored or tracked by WinkDrops after the search is complete.</p>
        
        <h3 className={commonStyles.h3}>5. Data Security</h3>
        <p className={commonStyles.p}>Since all data is stored locally on your device, you are responsible for securing your device. We do not transmit this personal data over the network or store it on any external servers.</p>
    </div>
);
